register/urls.py
# register/urls.py
from register import views
from django.conf.urls import url

# SET THE NAMESPACE!
app_name = 'register'
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

search/urls.py
# register/urls.py
from search import views
from django.conf.urls import url

app_name = 'search'

shopping/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from register import views
from search import views as search

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',search.index,name='index'),
    url(r'^register/',include('register.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

register/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

register/views.py
from django.shortcuts import render
from register.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'register/index.html')
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            login(request, user)
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request,'register/register.html',
                          {'user_form':user_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return render(request, 'register/login.html', {"error":"Invalid username or password"})
    else:
        return render(request, 'register/login.html', {})

search/views.py
import json

from django.shortcuts import render
from bs4 import BeautifulSoup
import requests

def index(request):
    products = []
    query = request.POST.get("search",False)
    if not query:
        return render(request, 'search/index.html')

    products += search_daraz_json(query)
    products += search_ishopping(query)
    products += search_saverspk(query)
    products += search_telemart(query)
    products = sorted(products, key=lambda k: k['price'])
    return render(request,'search/index.html',{"products":products})

def search_daraz(query):
    try:
        products = []
        url = "https://www.daraz.pk/catalog/?q=" + query
        resource = requests.get(url).text
        soup = BeautifulSoup(resource, "html.parser")
        list = soup.find_all(attrs = {"type": "application/ld+json"})[1].string
        list = json.loads(list)
        list = list["itemListElement"]
        for item in list:
            try:
                products.append(({"name": item["name"], "href": item["url"], "price": float(item["offers"]["price"]),
                                  "image": item["image"],"site":"Daraz.com"}))
            except:
                continue
        return products
    except Exception as e:
        return []

def search_daraz_json(query):
    try:
        products = []
        url = "https://www.daraz.pk/catalog/?_keyori=ssd&ajax=true&from=suggest_normal&q=" + query
        resource = requests.get(url).text
        list = json.loads(resource)
        list = list["mods"]["listItems"]
        for item in list:
            try:
                products.append(
                    ({"name": item["name"], "href": item["productUrl"], "price": float(item["price"]),
                      "image": item["image"], "site": "Daraz.com"}))
            except:
                continue
        return products
    except Exception as e:
        return []

def search_ishopping(query):
    try:
        products = []
        url = "https://eucs4.klevu.com/cloud-search/n-search/search?ticket=klevu-14920772243175751&paginationStartsFrom=0&sortPrice=false&ipAddress=undefined&analyticsApiKey=klevu-14920772243175751&showOutOfStockProducts=false&klevuFetchPopularTerms=false&klevu_priceInterval=500&fetchMinMaxPrice=true&klevu_multiSelectFilters=true&noOfResults=20&klevuSort=rel&enableFilters=true&filterResults=&visibility=search&category=KLEVU_PRODUCT&klevu_filterLimit=50&sv=1212&lsqt=&responseType=json&resultForZero=1&term=" + query
        resource = requests.get(url).text
        list = json.loads(resource)
        list = list["result"]
        for item in list:
            try:
                products.append(
                    ({"name": item["name"], "href": item["url"], "price": float(item["price"]),
                      "image": item["image"], "site": "Ishopping.com"}))
            except:
                continue
        return products
    except Exception as e:
        return []

def search_saverspk(query):
    try:
        products = []
        url = "https://www.searchanise.com/getwidgets?api_key=4S6h9h8k9i&restrictBy%5Bstatus%5D=A&restrictBy%5Bempty_categories%5D=N&restrictBy%5Busergroup_ids%5D=0%7C1&restrictBy%5Bcategory_usergroup_ids%5D=0%7C1&restrictBy%5Bapproved%5D=Y&restrictBy%5Bactive_company%5D=Y&startIndex=0&items=true&pages=true&facets=false&categories=true&suggestions=true&vendors=false&tags=false&pageStartIndex=0&pagesMaxResults=3&categoryStartIndex=0&categoriesMaxResults=3&suggestionsMaxResults=4&union%5Bprice%5D%5Bmin%5D=price_0%7Cprice_1&vendorsMaxResults=3&output=jsonp&callback=jQuery22404147613927260918_1584256529242&_=1584256529250&tagsMaxResults=3&maxResults=33&q=" + query
        resource = requests.get(url).text.split('"items":')[1].replace('});','')
        list = json.loads(resource)
        for item in list:
            try:
                products.append(
                    ({"name": item["title"], "href": item["link"], "price": float(item["price"]),
                      "image": item["image_link"], "site": "Savers.pk"}))
            except:
                continue
        return products
    except Exception as e:
        return []

def search_telemart(query):
    try:
        products = []
        url = "https://iw6vhpl077-3.algolianet.com/1/indexes/New_Telemart/query?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.32.1&x-algolia-application-id=IW6VHPL077&x-algolia-api-key=ee7d5abead68d64b082fe5d93d02ae78"
        data = {"params":"query={}&hitsPerPage=30".format(query)}
        resource = requests.post(url=url,json=data).text
        list = json.loads(resource)
        list = list["hits"]
        for item in list:
            try:
                if float(item["special_price"]) > 0:
                    products.append(
                        ({"name": item["name"], "href": item["url"], "price": float(item["special_price"]),
                          "image": item["image_url"], "site": "Telemart.pk"}))
            except:
                continue
        return products
    except Exception as e:
        return []

templates/register/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'site.css' %}">

</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            {# Django Home Link / Admin Link / Register Link#}
            <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
            {% if user.is_staff %}
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            {% endif %}

            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li style="margin-top: 13px;"><form method="post" action="{% url 'index' %}">
                {% csrf_token %}
                <input type="search" placeholder="Search.." name="search">
                <button type="submit"><i class="fa fa-search"></i></button>
            </form></li>

            {% else %}
            <li><a class="navbar-link" href="{% url 'register:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'register:user_login' %}">Login</a></li>
            {% endif %}

        </ul>
        {% if user.is_authenticated %}
        <div class="usr-info">{{user}}</div>
        {% endif %}
    </div>
</nav>
<div class="container-main">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

templates/register/index.html
{% extends "register/base.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome!</h1>
        {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        {% else %}
        <h2>Register or Login</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/register/login.html
{% extends 'register/base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron jumbotron-center">
        <h2>Login</h2>
        <form method="post" action="{% url 'register:user_login' %}">
            {% csrf_token %}
            {# A more "HTML" way of creating the login form#}
            <p>
<!--                <label for="username">Username:</label>-->
            <input type="text" name="username" placeholder="Username"></p>
            <p>
<!--                <label for="password">Password:</label>-->
            <input type="password" name="password" placeholder="Password"></p>
            <p>{{error}}</p>
            <input class="btn btn-primary" type="submit" name="" value="Login">
        </form>
    </div>
</div>
{% endblock %}

templates/register/register.html
{% extends "register/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="container">
    <div class="jumbotron jumbotron-center">
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h2>Register</h2>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input class="btn btn-primary" type="submit" name="" value="Register">
        </form>

        {% endif %}
    </div>
</div>
{% endblock %}

templates/search/index.html
{% extends "register/base.html" %}
{% block body_block %}
<div class="row product-list">
    {% for p in products %}
    <div class="prod-item col-md-3">
        <div class="prod-img">
            <img src={{p.image}} />
        </div>
        <div class="prod-name">
            <a target="_blank" href={{p.href}}>{{p.name}}</a>
        </div>
        <div class="prod-price">
            <span class="prod-price">Rs. {{p.price}}</span>
            <span class="prod-site pull-right">{{p.site}}</span>

        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}